### ISSUE TITLE
Suggestion: add "don't hover the mouse over any link while saving as PDF" to https://se-education.org/guides/tutorials/savingPdf.html

### ISSUE THREAD

**Issue by E0735389** [se-edu/guides#11]
As in the title. I suggest adding "don't hover the mouse over any link while saving as PDF" to https://se-education.org/guides/tutorials/savingPdf.html .

Reason: otherwise one of the link may look blackened and underlined like this.

![](https://raw.githubusercontent.com/tahsinhasem/ped/main/files/998c8eca-e540-40f6-8270-7420cd3fd20f.png)

**Comment by damithc** [comment]
Good suggestion, @E0735389 
Thanks 💯
