### ISSUE TITLE
Guides for mac is not updated

### ISSUE THREAD

**Issue by baskargopinath** [se-edu/guides#14]
On MacOS, preferences has been changed to settings. this is one instance in the guide where it appears wrongly @damithc should we update this for all the guides?

https://se-education.org/guides/tutorials/checkstyle.html

![image](https://github.com/se-edu/guides/assets/73015364/5db9ecc8-81bf-4018-9e31-1881cc37588a)
![image](https://github.com/se-edu/guides/assets/73015364/ebe36cf7-7baa-49f0-9cc8-a3e5515335d2)

**Comment by damithc** [comment]
@baskargopinath Thanks for reporting this. Yes, we should update this. If there is a chance that some are still using the older term, we can change it as: `Settings...` (previously called `Preferences...`)

**Comment by baskargopinath** [comment]
@damithc okay you can assign it to me if you want i will update all of the instances in
https://se-education.org/guides/

**Comment by baskargopinath** [comment]
File > Settings (Windows/Linux), or IntelliJ IDEA > Preferences…​ (macOS)

File > Settings (Windows/Linux), or IntelliJ IDEA > Settings…​  (previously called Preferences...) (macOS)

like this?

**Comment by baskargopinath** [comment]
![image](https://github.com/se-edu/guides/assets/73015364/e636b7c5-66b3-4eca-a114-b0346a4ef387)

point 2 also needs to be updated it only shows the windows version of going to settings

**Comment by damithc** [comment]
> File > Settings (Windows/Linux), or IntelliJ IDEA > Preferences…​ (macOS)
> 
> File > Settings (Windows/Linux), or IntelliJ IDEA > Settings…​ (previously called Preferences...) (macOS)
> 
> like this?

Hm... it is a bit noisy.  Do you know when did the term change from Preferences to Settings?

**Comment by baskargopinath** [comment]
with the release of ventura so around 2 years ago
https://www.reddit.com/r/MacOS/comments/yv6t8n/did_they_change_preferences_to_setting/

**Comment by damithc** [comment]
> with the release of ventura so around 2 years ago
> https://www.reddit.com/r/MacOS/comments/yv6t8n/did_they_change_preferences_to_setting/

I guess we can go ahead and change to `Settings` (i.e., no need to keep the older term). Older iOS users (which can't be many) will know the term was changed in newer versions.

**Comment by baskargopinath** [comment]
Ok
