### ISSUE TITLE
(Feature Request) Add Navigation Arrows to Related Topics

### ISSUE THREAD

**Issue by huizhuansam** [se-edu/guides#2]
It would be nice if there are intuitive directives to prompt the user to navigate to the next or previous page of a multi-page guide. For example, the JavaFX tutorial has 4 parts across 4 pages. Without the directives, some users might not be aware of other parts. Here is a sketch of what can be done:
![Screenshot 2021-09-10 at 10 00 54 AM](https://user-images.githubusercontent.com/64345999/132787248-f481c02b-019a-45ad-be85-92a4064c84c8.png)

**Comment by damithc** [comment]
@huizhuansam thanks for the suggestion. I've added something of that sort, for the time being.

![image](https://user-images.githubusercontent.com/1673303/132972410-b1fa6aa5-8601-4a89-986f-2592d5125ef8.png)
