### ISSUE TITLE
[JavaFX-Part 3] Refactor class DialogBox and method handleUserInput

### ISSUE THREAD

**Issue by JiaXinEu** [se-edu/guides#23]
### Current:
![image](https://github.com/se-edu/guides/assets/108446221/bd8705a4-5f30-444e-8fa4-68365643e2e0)
![image](https://github.com/se-edu/guides/assets/108446221/87bc9aa9-a83e-4610-a854-0e64168d9bb3)

### Problem:
Label and ImageView is created in handleUserInput and passed to DialogBox, which may increase dependency and reduce readability of code.

### Proposed:
Constructor of DialogBox can be something as below:
```
public DialogBox (String s, Image i) {
    text = new Label(s);
    displayPicture = new ImageView(i);
    // ...
}
```
handleUserInput can be something as below:
```
private void handleUserInput() {
    String userText = userInput.getText();
    String dukeText = getResponse(userInput.getText());
    dialogContainer.getChildren().addAll(
            new DialogBox(userText, user),
            new DialogBox(dukeText, duke)
    );
    userInput.clear();
}

```

**Comment by damithc** [comment]
@JiaXinEu You can send a PR for this.
