### ISSUE TITLE
[AB3: Tracing Code] Update tip boxes

### ISSUE THREAD

**Issue by ruth-lim** [se-edu/guides#24]
## Current
<img width="452" alt="Picture 1" src="https://github.com/se-edu/guides/assets/110249543/210dd84d-c798-4b8c-a808-e481f6a293bd">

## Problem
Inconsistency in the alert/tip boxes. This can make readers confused or feel that the content is very messy.

## Proposed
To standardise all tips (with the light bulbs) to be placed in the boxes. Certain tips can also be classified as “Note" or " Info" and be put in a different color box to avoid overwhelming the reader with too many tip boxes. 

_Note: This can be improved across all 3 tutorials._

**Comment by damithc** [comment]
@ruth-lim Tip box formatting has changed since we moved the tutorial out of AB3. Can you take a look at https://se-education.org/guides/tutorials/ab3TracingCode.html and see if this issue is still applicable?

**Comment by ruth-lim** [comment]
Closing this issue as it is no longer applicable after migrating out of AB3.
