### ISSUE TITLE
[JavaFX-Part2] Add UI screenshot to introduce different components of UI

### ISSUE THREAD

**Issue by laney0808** [se-edu/guides#27]
**Current:**
Uses a tree diagram to show the various nodes of the UI

<img width="451" alt="image" src="https://github.com/se-edu/guides/assets/122271269/7ebca972-9cd7-4190-bfd6-c9b6e10cc4d5">

Problem:
Does not reflect how this structure renders on the actual UI. May not be directly and immediately understandable.

Proposed:
Add a screenshot of the UI and label each component. Show the inclusion logic with the label.

**Comment by damithc** [comment]
@laney0808 Seems like a good suggestion. Go ahead and send a PR for this.
