### ISSUE TITLE
[JavaFX-Part2] Add in sample dialog box in example code

### ISSUE THREAD

**Issue by laney0808** [se-edu/guides#28]
**Current:**

<img width="468" alt="image" src="https://github.com/se-edu/guides/assets/122271269/a9da7073-06b3-44ce-bb04-28a84658b0e5">

**Problem:**
The code does not echo the tree diagram as there are no dialog boxes in the scroll pane. For the students to also learn about Vbox, Labels and Image View, instead of doing it later in this tutorial, this part of the code can include a sample dialog box.

**Proposed:**
Add in a temporary sample dialog box with image view and text label.

**Comment by damithc** [comment]
@laney0808 Will it disrupts the incremental building of the chatbot GUI? If not, you can send a PR to add this to the guide.

**Comment by laney0808** [comment]
> @laney0808 Will it disrupts the incremental building of the chatbot GUI? If not, you can send a PR to add this to the guide.

Hi Prof! My proposed plan is to move the "add custom control" section in part 3, where the DialogBox is declared, into part 2 so it fits inside part 2. Later in part 3, we can incrementally add in the handleInput method. So yes, I believe this does not disrupt the incremental building.

**Comment by laney0808** [comment]
Diffiulty met: as my system is MacOS, the screenshot of the mock up looks different from that of the original tutorial. Two solutions are possible: 1. ask anyone else in the team with Windows system to screenshot; 2. Change all screen shots to that on the MacOS system.

**Comment by damithc** [comment]
@laney0808 you can use the Mac screenshot for now. We can deal with it later.
