### ISSUE TITLE
[JavaFX - Part2] Additional tutorial for styling of components

### ISSUE THREAD

**Issue by laney0808** [se-edu/guides#29]
**Current:**
"Styling" section only include those for containers and user input box. It also only gives instructions on styling to get the example UI, without much explanation.

**Problem:**
Styling for dialog box elements is not specifically mentioned. It is only mentioned later in part 3, but it is more relevant to part 2. Furthermore, this part does mention that readers should refer to the official JavaFX documentation for a comprehensive list of properties to modify. However, some students may not read them especially when they are given a ready-for-use piece of code for their individual project. 

**Proposed:**
Also explore styling for Image View and text label. 
Mentions some of the most commonly-used properties for each element as examples. For example, wrapping in text label and scroll panel and binding of width and height can be mentioned. Provide explanation for lines of code whose purposes are not immediately understandable.

**Comment by damithc** [comment]
@laney0808 Check if the [new 'Part 5'](https://se-education.org/guides/tutorials/javaFxPart5.html) covers this aspect. If not, you can send a PR to propose your change (to part 2 or part 5).

**Comment by laney0808** [comment]
> [new 'Part 5'](https://se-education.org/guides/tutorials/javaFxPart5.html)

Hi Prof! I realized that part of it is mentioned in part 5, and the other part is already fixed in issue #29. I'll close this issue for now.
