### ISSUE TITLE
[JavaFX - Part3] Add introduction in part 3

### ISSUE THREAD

**Issue by laney0808** [se-edu/guides#30]
Current:
Has 3 parts: echoing the user, adding dialog boxes, and adding custom behavior to dialog boxes.

Problem:
Lacking an introduction to even handlers in general. Students may lack a general understanding of event handlers, and may face difficulties when using event handlers for different controls.

Proposed:
Introduce the general logic for event handlers, some common event handlers for different controls, and a link to more advanced event handlers that are not likely to be used in the Duke project for exploration.

**Comment by damithc** [comment]
@laney0808 You can send a PR for this.

**Comment by laney0808** [comment]
fixed by #71
