### ISSUE TITLE
[AB3: Tracing Code] Tips section

### ISSUE THREAD

**Issue by NeoHW** [se-edu/guides#32]
## Current
There is no common Debugging Tips/explanation section for new users

## Problem
Instead of jumping around between web pages or sections, it would be helpful to have a consolidated debugging tips section filled with the most important information and tips for beginners.

For example: Beginners might not know the differences between step-in and step-over.

## Proposed
Add a basic tips section that serves as a quick summary and refresher for students not used to the debugger.
This section will include tips about the debugger's different functionalities and usages.

**Comment by damithc** [comment]
Closing in favor of #20
