### ISSUE TITLE
[AB3: Tracing Code]: Clarify what Event Driven Mechanisms is 

### ISSUE THREAD

**Issue by tayruxin** [se-edu/guides#34]
**Current:**

![image](https://github.com/se-edu/guides/assets/106758300/1077d61c-7e33-419b-b9b8-55ca2ae658a7)

**Problem:**
Students might not understand what it means by “various event-driven mechanisms” and may be confused on the choice of placing the breakpoint where the UI transfer controls to the logic component. 

**Proposed:**
Add a paragraph after the highlighted part: 

This is because, unlike linear command-line programs, GUI applications respond to user actions (like clicks and keystrokes) and other events, triggering various event listeners and handlers. This non-linear flow of control can make it difficult to trace and debug the sequence of operations, as the program reacts dynamically to different events, creating an obscure execution path.

**Comment by tayruxin** [comment]
I think that will be a good solution as it does not make the whole tutorial lengthy and students who are unsure can refer to the additional information.

**Comment by damithc** [comment]
> I think that will be a good solution as it does not make the whole tutorial lengthy and students who are unsure can refer to the additional information.

👍 
Closing this issue.
