### ISSUE TITLE
[JavaFX - Part2] Change VBox to HBox

### ISSUE THREAD

**Issue by laney0808** [se-edu/guides#38]
**Current:**
ImageView and Label are shown as nodes in a VBox

<img width="378" alt="Screenshot 2024-07-06 at 16 52 56" src="https://github.com/se-edu/guides/assets/122271269/563491ba-1c48-499c-8dd1-e1d7f7c2bc75">

**Problem:**
According to the mockup screenshot, the ImageView and Label are in a HBox which forms the DialogBox, and the DialogBoxes are stacked in a VBox as the content of the ScrollPane.
**Proposed:**
Under the "VBox" node, we should have:
HBox -> VBox
ImageView -> HBox
Label -> HBox

**Comment by damithc** [comment]
@laney0808 What about the code given? Does it match the diagram or the mockup?

**Comment by laney0808** [comment]
> @laney0808 What about the code given? Does it match the diagram or the mockup?

Hi Prof! The code given does not seem to match the diagram or the mock up completely. The code for this part is only as detailed as the VBox (dialog container). It did not have dialog box (with HBox, ImageView, and Label). In the proposed version in #28, I already fixed the code by adding a sample dialog box. All that's left for this part is just to add a HBox as a container of ImageView and Label.

**Comment by laney0808** [comment]
> @laney0808 What about the code given? Does it match the diagram or the mockup?

Hi Prof! The code given does not seem to match the diagram or the mock up completely. The code for this part is only as detailed as the VBox (dialog container). It did not have dialog box (with HBox, ImageView, and Label). In the proposed version in #28, I already fixed the code by adding a sample dialog box. All that's left for this part is just to add a HBox as a container of ImageView and Label.

**Comment by laney0808** [comment]
fixed by #70

**Comment by laney0808** [comment]
fixed by #70
