### ISSUE TITLE
[JavaFX - Part2] Adjust identification and definition of ScrollPane

### ISSUE THREAD

**Issue by laney0808** [se-edu/guides#39]
**Current:**
 
<img width="468" alt="image" src="https://github.com/se-edu/guides/assets/122271269/31771822-88d4-40a5-bbc7-8ffa69dc2a94">

**Problem:**
1.	The text says “ScrollPane” but the image shows scrollbar
2.	The fact that ScrollPane is considered a Control maybe confusing to the students because it looks like a container and is also under “container” in Scene Builder although it extends Control class.
**Proposed:**
1.	Change the image for ScrollPane to the entire ScrollPane
2.	Briefly explain to the students that “ScrollPane” actually extends the Control class although it seems like a container due to its interactive feature.

**Comment by damithc** [comment]
@laney0808 Go ahead and submit a PR for this.

**Comment by laney0808** [comment]
fixed by #47
