### ISSUE TITLE
(Typo) "re" should be "are" in Automating the testing of text UIs

### ISSUE THREAD

**Issue by skylee03** [se-edu/guides#7]
In [Automating the testing of text UIs](https://se-education.org/guides/tutorials/textUiTesting.html), the first sentence of [Setting up](https://se-education.org/guides/tutorials/textUiTesting.html) is

> Given below re steps to set it up for a project.

I believe "re" is a corruption of "are".

**Comment by damithc** [comment]
Thanks for the bug report, @skylee03 
Fixed.
