### ISSUE TITLE
[AB3: Adding Command] Image Not Displaying in Markdown

### ISSUE THREAD

**Issue by mfjkri** [se-edu/guides#81]
### Description:
The embedded image is not displaying as expected. The issue appears to be caused by the $ symbol in the file path, which Markdown misinterprets as a math expression. Additionally, the .. in the file path is incorrect and should be removed.

### Current File Path:
```markdown
![$remark shows up in each entry](../images/add-remark/$Remark.png)
```

### Current Behavior:

![telegram-cloud-photo-size-5-6204136592319299127-y](https://github.com/user-attachments/assets/801c7ebe-6677-4f5f-b489-7340960b5b6d)

#### Proposed Solutions:
1. **Escape the `$` Symbol:**:
   ```markdown
   ![$remark shows up in each entry](images/add-remark/\$Remark.png)
   ```

2. **Rename the File:**
   ```markdown
   ![$remark shows up in each entry](images/add-remark/\Remark.png)
   ```

3. **Use HTML Syntax:**:
   ```html
   <img src="images/add-remark/$Remark.png" alt="$remark shows up in each entry">
   ```

**Comment by damithc** [comment]
@mfjkri Thanks for reporting this. Will you be submitting a PR?

**Comment by mfjkri** [comment]
Yup I can!
