### ISSUE TITLE
Broken link for Java Installation on index page

### ISSUE THREAD

**Issue by drustanyjt** [se-edu/guides#94]
On the https://se-education.org/guides/ website clicking on the highlighted link (Installation)
![Screenshot from 2024-09-30 17-01-05](https://github.com/user-attachments/assets/2574ea8d-d810-45b6-9c65-eb005b3e6c73)

Leads to this page https://se-education.org/guides/javaInstallation.html but shows an error.
![image](https://github.com/user-attachments/assets/94178fc3-c821-4229-ad3c-c54dcaa9efaf)

I think the intended display file should be https://github.com/se-edu/guides/blob/master/tutorials/javaInstallation.md. In which case the cause of the error is a typo in Line 21 of [index.md](https://github.com/se-edu/guides/blob/master/index.md?plain=1#L21).
![image](https://github.com/user-attachments/assets/109c37f4-124e-462c-9908-f54c20c44363)

It should probably be `tutorials/javaInstallation.html` instead of just `javaInstallation.html`.

An alternative would be to remove the hyperlink for the Installation subheading entirely.

**Comment by damithc** [comment]
Good catch @drustanyjt 
Fixed
