### ISSUE TITLE
Broken links in Java Installation Guides

### ISSUE THREAD

**Issue by mfjkri** [se-edu/guides#96]
It seems that two links in the [Java Installation Guide](https://se-education.org/guides/tutorials/javaInstallation.html) are broken.

The links in question are:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/89e524fd-b9b1-4475-9590-e38377dffb43">
<img width="300" alt="image" src="https://github.com/user-attachments/assets/6290be12-62af-4738-8405-386634923b2b">

It appears that these links should not include the `tutorials/` prefix in the path, as it is already present in the page URL (which was fixed in #94).

### Suggested fix to [tutorials/javaInstallation.md](https://github.com/se-edu/guides/blob/master/tutorials/javaInstallation.md?plain=1):
```md
* [**:fab-apple: Mac**](javaInstallationMac.html) -- If you are on a Mac and you anticipate using JavaFX in your projects, you are using the precise JDK specified in this guide.
* [**:fab-windows: Windows**](javaInstallationWindows.html)
```

**Comment by damithc** [comment]
Good catch, @mfjkri 
Fixed.
